### ISSUE TITLE
[Feature request] Apply to all segments

### ISSUE THREAD

**Issue by mrrezaie** [sebastianandress/Slicer-SurfaceWrapSolidify#4]
Hi,

It would be great if an operation (e.g. outer surface) could be applied to all visible segments by having a checkbox named "Apply to all segments" (the same as Smoothing).

**Comment by sebastianandress** [comment]
Hello, as the module settings are already very crowded and this functionality can easily be achieved via the Logic Operators module, I would not include this for now. However, if it is still very urgently needed, I can still add the feature.

![Logical Operator](https://github.com/sebastianandress/Slicer-SurfaceWrapSolidify/assets/10871206/b12503d6-ab45-4502-bea3-4e060ac44f41)
